# Generated by Django 6.0.2 on 2026-02-23 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa setu')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Data wydania')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa karty')),
                ('card_number', models.CharField(max_length=50, verbose_name='Numer karty')),
                ('card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='portfolio.cardset', verbose_name='Set')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('mint', 'Mint'), ('near_mint', 'Near Mint'), ('excellent', 'Excellent'), ('good', 'Good'), ('played', 'Played'), ('poor', 'Poor')], max_length=20, verbose_name='Stan')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards/', verbose_name='Zdjęcie')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='portfolio.card')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_instances', to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Zakup'), ('sale', 'Sprzedaż'), ('trade', 'Wymiana')], max_length=20, verbose_name='Typ transakcji')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota')),
                ('date', models.DateField(verbose_name='Data transakcji')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('card_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.cardinstance')),
            ],
        ),
    ]
